"""Widen numeric precision on signal_decisions

Revision ID: 7c89fc0a5082
Revises: e475c08e6e81
Create Date: 2026-03-16 12:24:20.475040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c89fc0a5082'
down_revision: Union[str, None] = 'e475c08e6e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signal_decisions', 'current_exposure_pct',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('signal_decisions', 'edge_at_signal',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('signal_decisions', 'edge_at_decision',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('signal_decisions', 'edge_erosion_pct',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signal_decisions', 'edge_erosion_pct',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('signal_decisions', 'edge_at_decision',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('signal_decisions', 'edge_at_signal',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('signal_decisions', 'current_exposure_pct',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
