"""make_wallet_tx_market_nullable

Revision ID: bc7c0224659c
Revises: 7c89fc0a5082
Create Date: 2026-03-16 13:23:25.498822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7c0224659c'
down_revision: Union[str, None] = '7c89fc0a5082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_transactions', 'market_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_transactions', 'market_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
