"""widen_wallet_score_precision

Revision ID: c24ff46d12e1
Revises: bc7c0224659c
Create Date: 2026-03-16 13:55:43.742077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24ff46d12e1'
down_revision: Union[str, None] = 'bc7c0224659c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_scores', 'hit_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'max_drawdown',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'market_diversity_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'concentration_penalty',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'consistency_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'suspiciousness_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'copyability_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'composite_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_scores', 'composite_score',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'copyability_score',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'suspiciousness_score',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'consistency_score',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'concentration_penalty',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'market_diversity_score',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'max_drawdown',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('wallet_scores', 'hit_rate',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
