"""Initial 20-table schema

Revision ID: e475c08e6e81
Revises: 
Create Date: 2026-03-16 12:14:58.886780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e475c08e6e81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latency_profiles',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('detection_delay_ms', sa.Integer(), nullable=False),
    sa.Column('decision_delay_ms', sa.Integer(), nullable=False),
    sa.Column('execution_delay_ms', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_relationships',
    sa.Column('market_a_id', sa.UUID(), nullable=False),
    sa.Column('market_b_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=True),
    sa.Column('asset_symbol', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('normal_spread_mean', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('normal_spread_std', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_a_id', 'market_b_id')
    )
    op.create_index('idx_market_rel_active', 'market_relationships', ['is_active', 'asset_symbol'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('raw_event_id', sa.BigInteger(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('best_bid', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('best_ask', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('midpoint', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('spread', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('bid_depth', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ask_depth', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('book_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_trade_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('open_interest', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_market_time', 'market_snapshots', ['market_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_table('markets',
    sa.Column('polymarket_id', sa.String(length=128), nullable=True),
    sa.Column('condition_id', sa.String(length=128), nullable=True),
    sa.Column('question', sa.String(length=1024), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_outcome', sa.String(length=32), nullable=True),
    sa.Column('fees_enabled', sa.Boolean(), nullable=False),
    sa.Column('fee_rate_bps', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('polymarket_id')
    )
    op.create_index('idx_markets_active', 'markets', ['is_active', 'category'], unique=False)
    op.create_index('idx_markets_condition', 'markets', ['condition_id'], unique=False)
    op.create_table('paper_fills',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fill_size', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('slippage', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fill_quality_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('book_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('levels_consumed', sa.Integer(), nullable=True),
    sa.Column('wavg_fill_price', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_orders',
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('position_group_id', sa.UUID(), nullable=True),
    sa.Column('leg_index', sa.SmallInteger(), nullable=False),
    sa.Column('is_hedge_leg', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('outcome', sa.String(length=8), nullable=True),
    sa.Column('order_type', sa.String(length=16), nullable=True),
    sa.Column('requested_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('requested_size', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('simulated_delay_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paper_orders_group', 'paper_orders', ['position_group_id'], unique=False, postgresql_where=sa.text('position_group_id IS NOT NULL'))
    op.create_table('paper_positions',
    sa.Column('position_group_id', sa.UUID(), nullable=True),
    sa.Column('leg_index', sa.SmallInteger(), nullable=False),
    sa.Column('is_hedge_leg', sa.Boolean(), nullable=False),
    sa.Column('target_structure', sa.String(length=32), nullable=True),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('source_wallet_id', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('outcome', sa.String(length=8), nullable=True),
    sa.Column('avg_entry_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_size', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('avg_exit_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('total_fees', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_slippage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_group', 'paper_positions', ['position_group_id'], unique=False, postgresql_where=sa.text('position_group_id IS NOT NULL'))
    op.create_index('idx_positions_status', 'paper_positions', ['status', sa.literal_column('opened_at DESC')], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('position_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('realized_pnl_cumulative', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('open_position_count', sa.Integer(), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('scenario', sa.String(length=16), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_run', 'portfolio_snapshots', ['run_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_index('idx_portfolio_time', 'portfolio_snapshots', [sa.literal_column('captured_at DESC')], unique=False)
    op.create_table('position_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('size', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('pnl_delta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('process_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_events_source_time', 'raw_events', ['source', sa.literal_column('received_at DESC')], unique=False)
    op.create_index('idx_raw_events_unprocessed', 'raw_events', ['processed', 'received_at'], unique=False, postgresql_where=sa.text('NOT processed'))
    op.create_table('replay_sessions',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speed_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scenario', sa.String(length=16), nullable=True),
    sa.Column('random_seed', sa.BigInteger(), nullable=True),
    sa.Column('is_deterministic', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_profiles',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('starting_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_position_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_total_exposure_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_correlated_positions', sa.Integer(), nullable=False),
    sa.Column('consecutive_loss_cooldown', sa.Integer(), nullable=False),
    sa.Column('kelly_fraction', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('daily_loss_stop_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_decisions',
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('reject_reason', sa.String(length=256), nullable=True),
    sa.Column('signal_age_ms', sa.Integer(), nullable=True),
    sa.Column('detection_to_decision_ms', sa.Integer(), nullable=True),
    sa.Column('price_at_decision', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('price_drift', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('spread_at_decision', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('kelly_fraction', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('proposed_size', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('available_bankroll', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('current_exposure_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('edge_at_signal', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('edge_at_decision', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('edge_erosion_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('scenario', sa.String(length=16), nullable=False),
    sa.Column('latency_profile_id', sa.UUID(), nullable=True),
    sa.Column('slippage_profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decisions_signal', 'signal_decisions', ['signal_id'], unique=False)
    op.create_table('slippage_profiles',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('base_slippage_bps', sa.Integer(), nullable=False),
    sa.Column('volatility_multiplier', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('depth_factor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('use_book_walking', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_runs',
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_signals',
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_wallet_id', sa.UUID(), nullable=True),
    sa.Column('market_id', sa.UUID(), nullable=True),
    sa.Column('related_market_id', sa.UUID(), nullable=True),
    sa.Column('relationship_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('model_probability', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('model_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('raw_edge', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('net_edge', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('spread_z_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('costs_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_strategy', 'trade_signals', ['strategy', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_signals_time', 'trade_signals', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('wallet_scores',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_roi', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('hit_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_position_size', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('avg_hold_time_seconds', sa.Integer(), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('market_diversity_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('concentration_penalty', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('consistency_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('suspiciousness_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('copyability_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('copy_decay_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'scored_at')
    )
    op.create_index('idx_wallet_scores_composite', 'wallet_scores', [sa.literal_column('composite_score DESC')], unique=False)
    op.create_index('idx_wallet_scores_wallet', 'wallet_scores', ['wallet_id', sa.literal_column('scored_at DESC')], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('raw_event_id', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detection_lag_ms', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('outcome', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('size', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('notional', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('source_sequence_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_tx_dedup', 'wallet_transactions', ['source_sequence_id'], unique=True, postgresql_where=sa.text('source_sequence_id IS NOT NULL'))
    op.create_index('idx_wallet_tx_market', 'wallet_transactions', ['market_id', sa.literal_column('detected_at DESC')], unique=False)
    op.create_index('idx_wallet_tx_occurred', 'wallet_transactions', ['wallet_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('idx_wallet_tx_wallet', 'wallet_transactions', ['wallet_id', sa.literal_column('detected_at DESC')], unique=False)
    op.create_table('wallets',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('proxy_address', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_index('idx_wallet_tx_wallet', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_occurred', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_market', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_dedup', table_name='wallet_transactions', postgresql_where=sa.text('source_sequence_id IS NOT NULL'))
    op.drop_table('wallet_transactions')
    op.drop_index('idx_wallet_scores_wallet', table_name='wallet_scores')
    op.drop_index('idx_wallet_scores_composite', table_name='wallet_scores')
    op.drop_table('wallet_scores')
    op.drop_index('idx_signals_time', table_name='trade_signals')
    op.drop_index('idx_signals_strategy', table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_table('strategy_runs')
    op.drop_table('slippage_profiles')
    op.drop_index('idx_decisions_signal', table_name='signal_decisions')
    op.drop_table('signal_decisions')
    op.drop_table('risk_profiles')
    op.drop_table('replay_sessions')
    op.drop_index('idx_raw_events_unprocessed', table_name='raw_events', postgresql_where=sa.text('NOT processed'))
    op.drop_index('idx_raw_events_source_time', table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_table('position_events')
    op.drop_index('idx_portfolio_time', table_name='portfolio_snapshots')
    op.drop_index('idx_portfolio_run', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('idx_positions_status', table_name='paper_positions')
    op.drop_index('idx_positions_group', table_name='paper_positions', postgresql_where=sa.text('position_group_id IS NOT NULL'))
    op.drop_table('paper_positions')
    op.drop_index('idx_paper_orders_group', table_name='paper_orders', postgresql_where=sa.text('position_group_id IS NOT NULL'))
    op.drop_table('paper_orders')
    op.drop_table('paper_fills')
    op.drop_index('idx_markets_condition', table_name='markets')
    op.drop_index('idx_markets_active', table_name='markets')
    op.drop_table('markets')
    op.drop_index('idx_snapshots_market_time', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index('idx_market_rel_active', table_name='market_relationships')
    op.drop_table('market_relationships')
    op.drop_table('latency_profiles')
    # ### end Alembic commands ###
